version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: docker/Dockerfile.backend
    restart: always
    env_file:
      - ../.env
    ports:
      - "3001:3001"
    volumes:
      - ../ImagesSite:/app/ImagesSite
    networks:
      - kbnet
