// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vmqybhofxnxtelczktsx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZtcXliaG9meG54dGVsY3prdHN4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NTY1OTIsImV4cCI6MjA2MzQzMjU5Mn0.b0xtoQau_nqwM7DXdtZ3soSWBlKM4THjVzTKaeX1iOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);